backend:
  name: github
  repo: drrakendu78/TradSC-docs
  branch: gh-pages
  base_url: https://auth.camp.codes
  auth_endpoint: oauth/authorize
  app_id: Ov23libyHLEeDGDw2C2i

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Accueil"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
